# -*- coding: utf-8 -*-
"""Subwaylines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ri742BTtiECIQhBrUBo2PDkFwCBqObcs
"""

import pandas as pd

# Load your uploaded CSV
df = pd.read_csv('subwayy.csv')

# Define groups based on MTA color groupings
color_groups = {
    "A, C, E": {"A", "C", "E"},
    "B, D, F, M": {"B", "D", "F", "M"},
    "N, Q, R, W": {"N", "Q", "R", "W"},
    "1, 2, 3": {"1", "2", "3"},
    "4, 5, 6": {"4", "5", "6"},
    "J, Z": {"J", "Z"},
    "L": {"L"},
    "G": {"G"},
    "S": {"S"},
    "7": {"7"}
}

# Function to assign group name if any route is in a group
def assign_group(name):
    if pd.isna(name):
        return ""
    routes = [r.strip().upper() for part in str(name).split('/') for r in part.split('-')]
    for group_name, group_set in color_groups.items():
        if any(route in group_set for route in routes):
            return group_name
    return "Other"

# Apply to DataFrame
df["Subway Group"] = df["Name"].apply(assign_group)

# Preview results
df[["Name", "Subway Group"]]

# Save to CSV
df.to_csv('subway_grouped.csv', index=False)

from google.colab import files
files.download('subway_grouped.csv')